name       : platformio
version    : 3.6.6
release    : 4
source     :
    - https://github.com/platformio/platformio-core/archive/v3.6.6.tar.gz : 09f213a5ac5530e49feaeb6c1877afd3a00098c77daf4141022174e01459f41e
license    : Apache-2.0
component  : programming.python
summary    : PlatformIO is an open source ecosystem for IoT development.
description: |
    PlatformIO is an open source ecosystem for IoT development. Cross-platform build system and library manager. Continuous and IDE integration. Arduino and MBED compatible. Ready for Cloud compiling.
builddeps  :
    - python-setuptools
rundeps    :
    - python-bottle
    - python-click
    - python-colorama
    - python-lockfile
    - python-pyserial
    - python-requests
    - python-semanticversion
setup      :
    sed -i 's/click>=5,<6/click>=>5/' setup.py
build      : |
    %python_setup
install    : |
    %python_install
