name       : platformio
version    : 3.0.1
release    : 2
source     :
    - https://github.com/platformio/platformio-core/archive/v3.0.1.tar.gz : f4ac60bf8c2bc8862d10e0dd66ab22b80a69e35335b2560f41a102242262f3d4
license    : Apache-2.0
component  : programming.python
summary    : PlatformIO is an open source ecosystem for IoT development.
description: |
    PlatformIO is an open source ecosystem for IoT development. Cross-platform build system and library manager. Continuous and IDE integration. Arduino and MBED compatible. Ready for Cloud compiling.
builddeps  :
    - python-setuptools
rundeps    :
    - python-click
    - python-colorama
    - python-lockfile
    - python-pyserial
    - python-requests
build      : |
    %python_setup
install    : |
    %python_install
