name       : platformio
version    : 5.2.3
release    : 9
source     :
    - https://github.com/platformio/platformio-core/archive/refs/tags/v5.2.3.tar.gz : c7288e3027a88ddd1f47168faecf9d5875930bd222effbc1da8b1be5fd328cf4
homepage   : https://platformio.org/
license    : Apache-2.0
component  : programming.python
summary    : PlatformIO is an open source ecosystem for IoT development.
description: |
    PlatformIO is an open source ecosystem for IoT development. Cross-platform build system and library manager. Continuous and IDE integration. Arduino and MBED compatible. Ready for Cloud compiling.
rundeps    :
    - python-bottle
    - python-click
    - python-colorama
    - python-lockfile
    - python-marshmallow
    - python-pyserial
    - python-pyelftools
    - python-requests
    - python-semanticversion
    - python-tabulate
setup      : |
    sed -i 's/click>=5,<6/click>=>5/' setup.py
build      : |
    %python3_setup
install    : |
    %python3_install
    install -Dm00644 scripts/99-platformio-udev.rules $installdir/usr/lib/udev/rules.d/99-platformio-udev.rules
