name       : platformio
version    : 6.1.4
release    : 11
source     :
    - https://github.com/platformio/platformio-core/archive/refs/tags/v6.1.4.tar.gz : aa23792fd9055cc08115f3fc5a80a3d6cb0551bdcad2a703bc4d556a5423beed
homepage   : https://platformio.org/
license    : Apache-2.0
component  : programming.python
summary    : PlatformIO is an open source ecosystem for IoT development
description: |
    PlatformIO is an open source ecosystem for IoT development. Cross-platform build system and library manager. Continuous and IDE integration. Arduino and MBED compatible. Ready for Cloud compiling.
rundeps    :
    - python-aiofiles
    - python-ajsonrpc
    - python-bottle
    - python-colorama
    - python-lockfile
    - python-marshmallow
    - python-pyserial
    - python-pyelftools
    - python-requests
    - python-semanticversion
    - python-starlette
    - python-tabulate
    - python-uvicorn
    - python-wsproto
build      : |
    %python3_setup
install    : |
    %python3_install
    install -Dm00644 scripts/99-platformio-udev.rules $installdir/usr/lib/udev/rules.d/99-platformio-udev.rules
