name       : platformio
version    : 4.3.4
release    : 5
source     :
    - https://github.com/platformio/platformio-core/archive/v4.3.4.tar.gz : 8c0cf78f855ba0ddc629176c900706fa2d2a0c2d92053e9a6a02f7e86f770725
homepage   : https://platformio.org/
license    : Apache-2.0
component  : programming.python
summary    : PlatformIO is an open source ecosystem for IoT development.
description: |
    PlatformIO is an open source ecosystem for IoT development. Cross-platform build system and library manager. Continuous and IDE integration. Arduino and MBED compatible. Ready for Cloud compiling.
rundeps    :
    - python-bottle
    - python-click
    - python-colorama
    - python-lockfile
    - python-marshmallow
    - python-pyserial
    - python-pyelftools
    - python-requests
    - python-semanticversion
    - python-tabulate
setup      : |
    sed -i 's/click>=5,<6/click>=>5/' setup.py
build      : |
    %python3_setup
install    : |
    %python3_install
    install -Dm00644 scripts/99-platformio-udev.rules $installdir/usr/lib/udev/rules.d/99-platformio-udev.rules
